# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7c2603c37fa7d662085469b7c2e3d59bb935412a80a9a5f2f8b98c90accf02ab03d050cea279de74f90de035aa216d2aa913e1d4e9985aae6d92eaa182b32fc

test:
  secret_key_base: b04b3c2bd001dc5865310ff13b5c7e850b61493116f3bfe1db5557613c454cd6c340c9f7fa5ce165bef7ca743e9f21a010056bf5e1169b254883d5d31b0f3ba9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
